FROM ros:humble-ros-base

# sudo docker run -it --network host --device /dev/ttyAMA0 --volume /home/ubuntu/:/mnt_folder -v /dev:/dev --device-cgroup-rule "c 81:* rmw" --device-cgroup-rule "c 189:* rmw" --rm mzandtheraspberrypi/mycobot-ros2:1.1.0

ENV ROS_WORKSPACE="/ros2_ws"

RUN mkdir -p ${ROS_WORKSPACE}
ENV TMP="/tmp"
RUN mkdir -p ${TMP}
RUN mkdir -p "${ROS_WORKSPACE}/src"
WORKDIR "${ROS_WORKSPACE}/src"

# installing realsense stuff
# image transport install here to try and get compressed images sending
# https://github.com/IntelRealSense/realsense-ros/issues/2329
RUN apt update
RUN apt install ros-humble-librealsense2* ros-humble*-image-transport* -y
RUN apt install ros-humble-realsense2-* -y

# install cobot stuff

# libgl1 is hidden dep of opencv
RUN apt install git nano python3-pip python3-colcon-common-extensions libgl1 -y

# opencv-python is a hidden dep of pymycobot
RUN pip install pymycobot==3.4.9 opencv-python numpy

# this is one of the last steps so that if we have to re-run we have the other stuff cached
RUN git clone --recurse-submodules https://github.com/VModugno/mycobot_communications

RUN pip install pyrealsense2
RUN sudo apt-get install -y ros-humble-cv-bridge ros-humble-vision-opencv

WORKDIR ${ROS_WORKSPACE}
RUN echo ". /opt/ros/humble/setup.bash" >> /root/.bashrc
RUN /bin/bash -c '. /opt/ros/humble/setup.bash; colcon build --symlink-install'

RUN echo ". /${ROS_WORKSPACE}/install/setup.bash" >> /root/.bashrc
RUN echo "alias mycobot-launch='ros2 launch mycobot_interface_2 mycobot_comms_launch.py use_realsense:=False'" >> /root/.bashrc
