FROM ros:humble-ros-base

RUN mkdir -p /home/ubuntu/ros2_ws/src

# libgl1 is hidden dep of opencv
RUN apt update && apt install git nano python3-pip python3-colcon-common-extensions libgl1 -y

WORKDIR /home/ubuntu/ros2_ws/src
RUN git clone https://github.com/VModugno/mycobot_communications

# opencv-python is a hidden dep of pymycobot
RUN pip install pymycobot==3.4.9 opencv-python numpy

WORKDIR /home/ubuntu/ros2_ws/
RUN /bin/bash -c '. /opt/ros/humble/setup.bash; colcon build --symlink-install'
