FROM ros:humble-ros-base

RUN mkdir -p /home/ubuntu/ros2_ws/src
WORKDIR /home/ubuntu/ros2_ws

RUN apt install git nano -y

RUN apt install python3-colcon-common-extensions -y

RUN git clone -b ros2 https://github.com/VModugno/mycobot_communications
RUN rm -rf mycobot_communications/mycobot_msgs
RUN rm -rf mycobot_communications/mycobot_interface

RUN colcon build --symlink-install
RUN source install/setup.bash